//! The rows of the Agents page: one per project, with how its AGENTS.md stands.

use skillmirror_core::agents::{FILE_NAME, FileState};
use skillmirror_core::scan::Target;

use crate::items::{Item, Note, Tone};
use crate::results::short_path;
use crate::session::{AgentProject, Session};

pub(crate) fn agent_rows(session: &Session) -> Result<Vec<Item>, String> {
    if let Err(message) = &session.agents.source {
        return Err(message.clone());
    }
    Ok(session.agents.projects.iter().map(row).collect())
}

fn row(entry: &AgentProject) -> Item {
    let (state, text, tone) = match &entry.state {
        FileState::Current => ("current", "up to date".to_string(), Tone::Quiet),
        FileState::Outdated => (
            "outdated",
            "the vault text changed".to_string(),
            Tone::Change,
        ),
        FileState::Missing => ("missing", "no AGENTS.md yet".to_string(), Tone::Quiet),
        FileState::NoBlock => (
            "no block",
            "no autogenerated block yet".to_string(),
            Tone::Quiet,
        ),
        FileState::Edited => (
            "edited",
            "edited by hand; needs agents sync --force".to_string(),
            Tone::Problem,
        ),
        FileState::Broken(why) => ("broken", why.clone(), Tone::Problem),
        FileState::Problem(why) => ("unusable", format!("AGENTS.md {why}"), Tone::Problem),
    };
    Item {
        name: short_path(&entry.project.to_string_lossy()),
        detail: state.to_string(),
        note: Some(Note { text, tone }),
        targets: vec![Target {
            project: entry.project.clone(),
            skill: FILE_NAME.to_string(),
            path: entry.project.join(FILE_NAME),
        }],
        // What the text changed is what the page is for; making new files is the user's choice.
        preselected: entry.state == FileState::Outdated,
        card: Vec::new(),
    }
}
