use super::block::{END_LINE, Found, Search, checksum, render, search, with_endings};

fn found(content: &str) -> Found {
    match search(content) {
        Search::Found(f) => f,
        other => panic!("expected a block, got {other:?}"),
    }
}

#[test]
fn a_rendered_block_is_found_again_with_its_text_and_checksum() {
    let block = render("# Rules\n\n1. one");

    let f = found(&block);

    assert_eq!(f.body, "# Rules\n\n1. one");
    assert_eq!(f.recorded, Some(checksum("# Rules\n\n1. one")));
    assert_eq!((f.start, f.end), (0, block.len()));
}

#[test]
fn the_checksum_is_fixed_because_it_is_stored_in_user_files() {
    // FNV-1a 64 test vectors; a change here would mark every written block as hand-edited.
    assert_eq!(checksum(""), 0xcbf2_9ce4_8422_2325);
    assert_eq!(checksum("a"), 0xaf63_dc4c_8601_ec8c);
    assert_eq!(checksum("foobar"), 0x8594_4171_f739_67e8);
}

#[test]
fn text_around_the_block_is_not_part_of_it() {
    let content = format!("intro\n\n{}\n## Mine\nkeep\n", render("text"));

    let f = found(&content);

    assert_eq!(f.body, "text");
    assert_eq!(&content[..f.start], "intro\n\n");
    assert_eq!(&content[f.end..], "\n## Mine\nkeep\n");
}

#[test]
fn a_file_without_markers_has_no_block() {
    assert_eq!(search("# Title\n\nsome text\n"), Search::None);
    assert_eq!(search(""), Search::None);
}

#[test]
fn a_marker_in_the_middle_of_a_line_is_only_text() {
    let content = format!("see `{END_LINE}` in the docs\n");

    assert_eq!(search(&content), Search::None);
}

#[test]
fn crlf_files_are_read_the_same_and_the_body_is_normalised() {
    let block = with_endings(&render("a\nb"), true);

    let f = found(&block);

    assert_eq!(f.body, "a\nb");
    assert_eq!(f.recorded, Some(checksum("a\nb")));
    assert_eq!(f.end, block.len());
}

#[test]
fn a_block_at_the_end_of_a_file_without_a_final_newline_ends_at_the_file_end() {
    let content = render("x").trim_end().to_string();

    let f = found(&content);

    assert_eq!(f.end, content.len());
    assert_eq!(f.body, "x");
}

#[test]
fn an_empty_block_has_an_empty_body() {
    let content = format!("{}\n{END_LINE}\n", render("").lines().next().unwrap());

    assert_eq!(found(&content).body, "");
}

#[test]
fn a_begin_marker_without_a_checksum_is_found_with_none() {
    let content = format!("<!-- skillmirror:autogenerated begin -->\nx\n{END_LINE}\n");

    assert_eq!(found(&content).recorded, None);
}

#[test]
fn a_garbled_checksum_counts_as_none() {
    let content = format!(
        "<!-- skillmirror:autogenerated begin checksum=zzzzzzzzzzzzzzzz -->\nx\n{END_LINE}\n"
    );

    assert_eq!(found(&content).recorded, None);
}

fn broken(content: &str) -> String {
    match search(content) {
        Search::Broken(why) => why,
        other => panic!("expected a broken block, got {other:?}"),
    }
}

#[test]
fn a_begin_without_an_end_is_broken_and_names_the_line() {
    let content = format!(
        "title\n{}x\n",
        render("").lines().next().unwrap().to_string() + "\n"
    );

    assert!(broken(&content).contains("line 2 has no end marker"));
}

#[test]
fn an_end_without_a_begin_is_broken() {
    assert!(broken(&format!("x\n{END_LINE}\n")).contains("end marker at line 2"));
}

#[test]
fn two_blocks_are_broken_and_so_are_nested_begins() {
    let one = render("a");

    assert!(broken(&format!("{one}{one}")).contains("second autogenerated block"));
    let begin = one.lines().next().unwrap();
    assert!(broken(&format!("{begin}\n{begin}\n{END_LINE}\n")).contains("second begin marker"));
}
