//! The autogenerated block inside a project's AGENTS.md: how it is written, found and checked.
//!
//! ```text
//! <!-- skillmirror:autogenerated begin checksum=0123456789abcdef; do not edit ... -->
//! the text from the vault
//! <!-- skillmirror:autogenerated end -->
//! ```
//!
//! The checksum is of the text the tool wrote. It tells a block that is merely out of date (the vault text
//! changed) from a block somebody edited by hand, which is never replaced unseen.

pub(super) const BEGIN_PREFIX: &str = "<!-- skillmirror:autogenerated begin";
pub(super) const END_LINE: &str = "<!-- skillmirror:autogenerated end -->";
const NOTE: &str = "do not edit inside this block, edit project-files/AGENTS.md in the vault and run: skillmirror agents sync";

/// FNV-1a over the bytes. Not a security measure: it only has to notice an edit, and to stay the same in
/// every release because it is stored in the user's files.
pub(super) fn checksum(body: &str) -> u64 {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in body.bytes() {
        hash ^= u64::from(byte);
        hash = hash.wrapping_mul(0x0100_0000_01b3);
    }
    hash
}

/// The last lines of every block: they say, in plain Markdown, where the part of the project starts.
const FOOTER: &str = "---\n\n*Managed by skillmirror. Everything above this line can be updated automatically, so please change only what comes below it.*";

/// What sits between the markers for the vault text `text`: the text, then [`FOOTER`]. The checksum and the
/// comparison with a block found in a file are both over this.
pub(super) fn body(text: &str) -> String {
    format!("{text}\n\n{FOOTER}")
}

/// The block for the vault text `text`, with `\n` line ends and a newline after the end marker.
pub(super) fn render(text: &str) -> String {
    let body = body(text);
    format!(
        "{BEGIN_PREFIX} checksum={:016x}; {NOTE} -->\n{body}\n{END_LINE}\n",
        checksum(&body)
    )
}

/// `\n` line ends turned into `\r\n` for a file that uses them.
pub(super) fn with_endings(text: &str, crlf: bool) -> String {
    if crlf {
        text.replace('\n', "\r\n")
    } else {
        text.to_string()
    }
}

/// A block found in a file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(super) struct Found {
    /// Byte offset of the start of the begin line.
    pub(super) start: usize,
    /// Byte offset after the end line and its line end (or the end of the file).
    pub(super) end: usize,
    /// The checksum the begin line carries; `None` when it is missing or not a 16 digit hex number.
    pub(super) recorded: Option<u64>,
    /// What is between the markers, with `\n` line ends and without the newline before the end marker.
    pub(super) body: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(super) enum Search {
    None,
    Found(Found),
    /// Markers that do not make exactly one block; the text says what is wrong.
    Broken(String),
}

struct Open {
    start: usize,
    body_start: usize,
    recorded: Option<u64>,
    line: usize,
}

/// Looks for the block. A marker counts only at the start of a line.
pub(super) fn search(content: &str) -> Search {
    let mut open: Option<Open> = None;
    let mut found: Option<Found> = None;
    let mut offset = 0;
    for (index, raw) in content.split_inclusive('\n').enumerate() {
        let line_no = index + 1;
        // A byte order mark in front of the first line belongs to the file, not to a marker after it.
        let bom = if index == 0 && raw.starts_with('\u{feff}') {
            '\u{feff}'.len_utf8()
        } else {
            0
        };
        let text = raw[bom..].trim_end_matches(['\r', '\n']);
        if text.starts_with(BEGIN_PREFIX) && text.ends_with("-->") {
            if let Some(first) = &open {
                return Search::Broken(format!(
                    "a second begin marker at line {line_no} before the end marker of the one at line {}",
                    first.line
                ));
            }
            if found.is_some() {
                return Search::Broken(format!(
                    "a second autogenerated block starts at line {line_no}; a file holds one"
                ));
            }
            open = Some(Open {
                start: offset + bom,
                body_start: offset + raw.len(),
                recorded: recorded_checksum(text),
                line: line_no,
            });
        } else if text == END_LINE {
            let Some(begin) = open.take() else {
                return Search::Broken(format!(
                    "an end marker at line {line_no} without a begin marker before it"
                ));
            };
            found = Some(Found {
                start: begin.start,
                end: offset + raw.len(),
                recorded: begin.recorded,
                body: body_between(content, begin.body_start, offset),
            });
        }
        offset += raw.len();
    }
    if let Some(begin) = open {
        return Search::Broken(format!(
            "the begin marker at line {} has no end marker",
            begin.line
        ));
    }
    found.map_or(Search::None, Search::Found)
}

fn recorded_checksum(begin_line: &str) -> Option<u64> {
    let digits = begin_line.split("checksum=").nth(1)?.get(..16)?;
    u64::from_str_radix(digits, 16).ok()
}

fn body_between(content: &str, from: usize, to: usize) -> String {
    let raw = content
        .get(from..to)
        .unwrap_or_default()
        .replace("\r\n", "\n");
    raw.strip_suffix('\n').unwrap_or(&raw).to_string()
}
