//! Looking at a project's AGENTS.md and saying what state its block is in. Reads, never writes.

use std::path::{Path, PathBuf};

use super::block::{Found, Search, body, checksum, search};
use super::text::{FILE_NAME, Source};

/// Files above this size are not read: an AGENTS.md is a page of text, not a download.
const MAX_BYTES: u64 = 1024 * 1024;

/// How a project's AGENTS.md stands against the text.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FileState {
    /// There is no AGENTS.md.
    Missing,
    /// The file exists and has no autogenerated block: it is all the project's own.
    NoBlock,
    /// The block holds the text.
    Current,
    /// The block is what the tool wrote earlier, and the text has changed since.
    Outdated,
    /// The block was changed by hand, so it differs from what the tool wrote.
    Edited,
    /// The markers do not make one block; the text says what is wrong.
    Broken(String),
    /// The file cannot be used (a link, not a regular file, too large, not UTF-8, unreadable).
    Problem(String),
}

impl FileState {
    /// A word for tables.
    pub fn label(&self) -> &'static str {
        match self {
            Self::Missing => "missing",
            Self::NoBlock => "no block",
            Self::Current => "current",
            Self::Outdated => "outdated",
            Self::Edited => "edited",
            Self::Broken(_) => "broken",
            Self::Problem(_) => "problem",
        }
    }

    /// The reason, for the two states that have one.
    pub fn detail(&self) -> Option<&str> {
        match self {
            Self::Broken(why) | Self::Problem(why) => Some(why),
            _ => None,
        }
    }
}

/// What was read, so planning does not read the file twice.
#[derive(Debug, Clone)]
pub(super) struct Inspection {
    pub(super) path: PathBuf,
    pub(super) state: FileState,
    /// The whole file, when it was read.
    pub(super) content: Option<String>,
    pub(super) block: Option<Found>,
}

/// The state of `<project>/AGENTS.md`.
pub fn inspect_project(project: &Path, source: &Source) -> FileState {
    inspect(project, source).state
}

pub(super) fn inspect(project: &Path, source: &Source) -> Inspection {
    let path = project.join(FILE_NAME);
    let done = |state: FileState| Inspection {
        path: path.clone(),
        state,
        content: None,
        block: None,
    };
    let meta = match fs_err::symlink_metadata(&path) {
        Ok(meta) => meta,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return done(FileState::Missing),
        Err(e) => return done(FileState::Problem(format!("cannot be read: {e}"))),
    };
    if meta.file_type().is_symlink() {
        return done(FileState::Problem(
            "is a link; nothing is written through links".to_string(),
        ));
    }
    if !meta.is_file() {
        return done(FileState::Problem("is not a regular file".to_string()));
    }
    if meta.len() > MAX_BYTES {
        return done(FileState::Problem("is larger than 1 MiB".to_string()));
    }
    let content = match fs_err::read(&path) {
        Ok(bytes) => match String::from_utf8(bytes) {
            Ok(text) => text,
            Err(_) => return done(FileState::Problem("is not valid UTF-8".to_string())),
        },
        Err(e) => return done(FileState::Problem(format!("cannot be read: {e}"))),
    };
    let (state, block) = classify(&content, source);
    Inspection {
        path,
        state,
        content: Some(content),
        block,
    }
}

fn classify(content: &str, source: &Source) -> (FileState, Option<Found>) {
    match search(content) {
        Search::None => (FileState::NoBlock, None),
        Search::Broken(why) => (FileState::Broken(why), None),
        Search::Found(found) => {
            let state = if found.body == body(source.text()) {
                FileState::Current
            } else if found.recorded == Some(checksum(&found.body)) {
                FileState::Outdated
            } else {
                FileState::Edited
            };
            (state, Some(found))
        }
    }
}
