use std::os::unix::fs::symlink;

use super::block::{body, render, with_endings};
use super::inspect::{FileState, inspect_project};
use super::text::Source;
use crate::testutil::TempTree;

fn state(project: &TempTree) -> FileState {
    inspect_project(project.path(), &Source::builtin())
}

fn current_block() -> String {
    render(Source::builtin().text())
}

#[test]
fn no_file_is_missing() {
    assert_eq!(state(&TempTree::new()), FileState::Missing);
}

#[test]
fn a_file_without_markers_has_no_block() {
    let project = TempTree::new();
    project.write("AGENTS.md", "# My project\n\nrules\n");

    assert_eq!(state(&project), FileState::NoBlock);
}

#[test]
fn a_block_with_the_text_is_current_wherever_it_sits() {
    let project = TempTree::new();
    project.write(
        "AGENTS.md",
        &format!("top\n\n{}\n## Mine\nkeep\n", current_block()),
    );

    assert_eq!(state(&project), FileState::Current);
}

#[test]
fn a_crlf_file_with_the_text_is_current() {
    let project = TempTree::new();
    project.write("AGENTS.md", &with_endings(&current_block(), true));

    assert_eq!(state(&project), FileState::Current);
}

#[test]
fn a_block_the_tool_wrote_from_an_older_text_is_outdated() {
    let project = TempTree::new();
    project.write("AGENTS.md", &render("# Old text\n\n1. old"));

    assert_eq!(state(&project), FileState::Outdated);
}

#[test]
fn a_block_changed_by_hand_is_edited_not_outdated() {
    let project = TempTree::new();
    project.write(
        "AGENTS.md",
        &render("# Old text\n\n1. old").replace("1. old", "1. old and my own line"),
    );

    assert_eq!(state(&project), FileState::Edited);
}

#[test]
fn a_hand_edit_of_the_current_text_is_edited() {
    let project = TempTree::new();
    project.write(
        "AGENTS.md",
        &current_block().replace("Don't use AI agents", "Use AI agents"),
    );

    assert_eq!(state(&project), FileState::Edited);
}

#[test]
fn a_block_without_a_checksum_cannot_be_proved_untouched_so_it_is_edited() {
    let project = TempTree::new();
    project.write(
        "AGENTS.md",
        "<!-- skillmirror:autogenerated begin -->\nold\n<!-- skillmirror:autogenerated end -->\n",
    );

    assert_eq!(state(&project), FileState::Edited);
}

#[test]
fn a_body_equal_to_the_text_is_current_even_when_the_checksum_is_stale() {
    let project = TempTree::new();
    let body = body(Source::builtin().text());
    project.write(
        "AGENTS.md",
        &format!(
            "<!-- skillmirror:autogenerated begin checksum=0000000000000000 -->\n{body}\n<!-- skillmirror:autogenerated end -->\n"
        ),
    );

    assert_eq!(state(&project), FileState::Current);
}

#[test]
fn a_block_from_before_the_note_existed_is_outdated_so_that_sync_brings_the_note_in() {
    let project = TempTree::new();
    let text = Source::builtin().text().to_string();
    let sum = super::block::checksum(&text);
    project.write(
        "AGENTS.md",
        &format!(
            "<!-- skillmirror:autogenerated begin checksum={sum:016x} -->\n{text}\n<!-- skillmirror:autogenerated end -->\n"
        ),
    );

    assert_eq!(state(&project), FileState::Outdated);
}

#[test]
fn taking_the_note_out_of_the_block_by_hand_is_an_edit() {
    let project = TempTree::new();
    let block = current_block();
    let note_start = block.find("---\n\n*Managed").unwrap();
    let end = block.find("<!-- skillmirror:autogenerated end").unwrap();
    project.write(
        "AGENTS.md",
        &format!("{}{}", &block[..note_start], &block[end..]),
    );

    assert_eq!(state(&project), FileState::Edited);
}

#[test]
fn broken_markers_are_reported_with_the_reason() {
    let project = TempTree::new();
    project.write("AGENTS.md", "<!-- skillmirror:autogenerated end -->\n");

    let state = state(&project);

    assert_eq!(state.label(), "broken");
    assert!(state.detail().unwrap().contains("without a begin marker"));
}

fn problem(project: &TempTree) -> String {
    match state(project) {
        FileState::Problem(why) => why,
        other => panic!("expected a problem, got {other:?}"),
    }
}

#[test]
fn a_link_is_a_problem_and_is_never_followed() {
    let project = TempTree::new();
    project.write("elsewhere.md", &current_block());
    symlink(
        project.path().join("elsewhere.md"),
        project.path().join("AGENTS.md"),
    )
    .unwrap();

    assert!(problem(&project).contains("is a link"));
}

#[test]
fn a_folder_a_big_file_and_a_non_utf8_file_are_problems() {
    let project = TempTree::new();
    std::fs::create_dir(project.path().join("AGENTS.md")).unwrap();
    assert!(problem(&project).contains("not a regular file"));

    std::fs::remove_dir(project.path().join("AGENTS.md")).unwrap();
    std::fs::write(
        project.path().join("AGENTS.md"),
        "x".repeat(1024 * 1024 + 1),
    )
    .unwrap();
    assert!(problem(&project).contains("larger than 1 MiB"));

    std::fs::write(project.path().join("AGENTS.md"), [0xff, 0x00, 0xfe]).unwrap();
    assert!(problem(&project).contains("not valid UTF-8"));
}
