//! The AGENTS.md of a project: one autogenerated block filled from the vault's text, and the rest of the
//! file left to the project. Creating, checking and updating the block all go through here.

mod apply;
mod block;
mod error;
mod inspect;
mod plan;
mod seed;
mod text;

pub use apply::{AgentsReport, Applied, Written, apply_agents};
pub use error::AgentsError;
pub use inspect::{FileState, inspect_project};
pub use plan::{Action, AgentsEntry, AgentsPlan, Intent, installed_skills, plan_agents};
pub use seed::{plan_seed, seed_vault_text};
pub use text::{
    BUILTIN_SKILLS, FILE_NAME, Origin, Source, VAULT_FOLDER, load_source, vault_text_path,
};

#[cfg(test)]
mod apply_tests;
#[cfg(test)]
mod block_tests;
#[cfg(test)]
mod inspect_tests;
#[cfg(test)]
mod plan_tests;
#[cfg(test)]
mod seed_tests;
#[cfg(test)]
mod text_tests;
#[cfg(test)]
mod undo_tests;
