//! What a command would do to the AGENTS.md of each project. Reads, never writes.

use std::path::PathBuf;

use similar::TextDiff;

use super::block::{render, with_endings};
use super::inspect::{FileState, Inspection, inspect};
use super::text::Source;

/// What the command may do.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct Intent {
    /// Make the file, or put the block into a file that has none.
    pub create: bool,
    /// Rewrite a block that is out of date.
    pub update: bool,
    /// Also replace a block that was edited by hand.
    pub force: bool,
}

impl Intent {
    /// `agents add` and `init`: where there is no block.
    pub const ADD: Self = Self {
        create: true,
        update: false,
        force: false,
    };
    /// `agents sync`: where the block is out of date.
    pub const SYNC: Self = Self {
        create: false,
        update: true,
        force: false,
    };
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Action {
    /// A new file holding the block.
    Create,
    /// The block goes to the top of a file that has none; the rest stays.
    Insert,
    /// The block is rewritten; the rest stays.
    Update,
    Unchanged,
    /// Not what this command is for; the text says what is.
    Skipped(&'static str),
    Failed(String),
}

#[derive(Debug, Clone)]
pub struct AgentsEntry {
    pub project: PathBuf,
    /// `<project>/AGENTS.md`.
    pub path: PathBuf,
    pub state: FileState,
    pub action: Action,
    /// The file as it was planned against; apply checks it again.
    pub(crate) before: Option<String>,
    /// The whole file as it will be.
    pub(crate) after: Option<String>,
}

impl AgentsEntry {
    /// A unified diff of the file now and after; empty when nothing changes.
    pub fn diff(&self) -> String {
        let Some(after) = &self.after else {
            return String::new();
        };
        let now = self.before.as_deref().unwrap_or_default();
        TextDiff::from_lines(now, after.as_str())
            .unified_diff()
            .context_radius(3)
            .header("AGENTS.md now", "AGENTS.md after")
            .to_string()
    }

    /// Whether the entry writes anything.
    pub fn writes(&self) -> bool {
        matches!(
            self.action,
            Action::Create | Action::Insert | Action::Update
        )
    }
}

#[derive(Debug, Clone)]
pub struct AgentsPlan {
    pub entries: Vec<AgentsEntry>,
    pub source: Source,
}

impl AgentsPlan {
    pub fn changes(&self) -> usize {
        self.entries.iter().filter(|e| e.writes()).count()
    }

    pub fn failed(&self) -> usize {
        self.count(|a| matches!(a, Action::Failed(_)))
    }

    pub fn count(&self, pick: impl Fn(&Action) -> bool) -> usize {
        self.entries.iter().filter(|e| pick(&e.action)).count()
    }
}

/// Plans `intent` for each project, in the order given.
pub fn plan_agents(projects: &[PathBuf], source: &Source, intent: Intent) -> AgentsPlan {
    let entries = projects
        .iter()
        .map(|project| entry_of(project, inspect(project, source), source, intent))
        .collect();
    AgentsPlan {
        entries,
        source: source.clone(),
    }
}

fn entry_of(
    project: &std::path::Path,
    seen: Inspection,
    source: &Source,
    intent: Intent,
) -> AgentsEntry {
    let before = seen.content.clone();
    let crlf = before.as_deref().is_some_and(|c| c.contains("\r\n"));
    let block = with_endings(&render(source.text()), crlf);
    let (action, after) = match (&seen.state, intent) {
        (FileState::Current, _) => (Action::Unchanged, None),
        (FileState::Missing, i) if i.create => (Action::Create, Some(block)),
        (FileState::Missing, _) => (
            Action::Skipped("there is no AGENTS.md; `agents add` makes one"),
            None,
        ),
        (FileState::NoBlock, i) if i.create => (Action::Insert, before.as_deref().map(|c| put_first(c, &block, crlf))),
        (FileState::NoBlock, _) => (
            Action::Skipped("the file has no autogenerated block; `agents add` puts one in"),
            None,
        ),
        (FileState::Outdated, i) if i.update => (Action::Update, replaced(&seen, &block)),
        (FileState::Outdated, _) => (
            Action::Skipped("the block is out of date; `agents sync` updates it"),
            None,
        ),
        (FileState::Edited, i) if i.update && i.force => (Action::Update, replaced(&seen, &block)),
        (FileState::Edited, i) if i.update => (
            Action::Failed(
                "the autogenerated block was edited by hand; --force replaces it (the old file is kept for `undo`)"
                    .to_string(),
            ),
            None,
        ),
        (FileState::Edited, _) => (
            Action::Skipped("the block was edited by hand; `agents sync --force` replaces it"),
            None,
        ),
        (FileState::Broken(why), _) => (
            Action::Failed(format!("the markers are broken ({why}); fix them by hand")),
            None,
        ),
        (FileState::Problem(why), _) => (Action::Failed(format!("AGENTS.md {why}")), None),
    };
    AgentsEntry {
        project: project.to_path_buf(),
        path: seen.path,
        state: seen.state,
        action,
        before,
        after,
    }
}

/// The block in front of a file that has none, with a blank line between it and the rest.
fn put_first(content: &str, block: &str, crlf: bool) -> String {
    let (bom, rest) = match content.strip_prefix('\u{feff}') {
        Some(rest) => ("\u{feff}", rest),
        None => ("", content),
    };
    format!("{bom}{block}{}{rest}", with_endings("\n", crlf))
}

/// The file with the old block replaced; the text around it is byte for byte the same.
fn replaced(seen: &Inspection, block: &str) -> Option<String> {
    let (content, found) = (seen.content.as_deref()?, seen.block.as_ref()?);
    let old = content.get(found.start..found.end)?;
    // A block at the very end of a file that has no final newline keeps having none.
    let block = if old.ends_with('\n') {
        block
    } else {
        block.trim_end_matches(['\r', '\n'])
    };
    Some(format!(
        "{}{block}{}",
        content.get(..found.start)?,
        content.get(found.end..)?
    ))
}
