//! The text that fills the block: the vault's own AGENTS.md when it has one, otherwise the built-in text.
//! The layering is deliberate and shown wherever the text is used; a vault file that cannot be used is an
//! error, never a silent drop back to the built-in text.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use super::AgentsError;
use super::block::{BEGIN_PREFIX, END_LINE};

/// The file name, in the vault and in every project.
pub const FILE_NAME: &str = "AGENTS.md";

const BUILTIN: &str = include_str!("builtin.md");
/// The skills the built-in text tells an agent to use. A project without them gets no AGENTS.md from
/// `init` or `agents add`, because the file would point at nothing.
pub const BUILTIN_SKILLS: &[&str] = &["doc-start", "coding", "file-tree-optimization"];
const MAX_BYTES: u64 = 64 * 1024;

/// Where the text came from.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Origin {
    Builtin,
    Vault(PathBuf),
}

/// The text of the block, with `\n` line ends and no trailing newline.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Source {
    text: String,
    origin: Origin,
}

impl Source {
    pub fn builtin() -> Self {
        Self {
            text: normalise(BUILTIN),
            origin: Origin::Builtin,
        }
    }

    pub fn text(&self) -> &str {
        &self.text
    }

    pub fn origin(&self) -> &Origin {
        &self.origin
    }

    /// Where the text came from, for output.
    pub fn describe(&self) -> String {
        match &self.origin {
            Origin::Builtin => "the built-in text".to_string(),
            Origin::Vault(path) => path.display().to_string(),
        }
    }

    /// Skills the text relies on. Only the built-in text is known; a vault file is the owner's business.
    pub fn required_skills(&self) -> &'static [&'static str] {
        match self.origin {
            Origin::Builtin => BUILTIN_SKILLS,
            Origin::Vault(_) => &[],
        }
    }
}

impl Source {
    /// Fails, naming what is missing, when the text relies on skills that `project` would not have. Nothing
    /// is checked for a vault text.
    pub fn require_skills(
        &self,
        project: &Path,
        have: &BTreeSet<String>,
    ) -> Result<(), AgentsError> {
        let missing: Vec<&str> = self
            .required_skills()
            .iter()
            .copied()
            .filter(|skill| !have.contains(*skill))
            .collect();
        if missing.is_empty() {
            return Ok(());
        }
        Err(AgentsError::MissingSkills {
            project: project.to_path_buf(),
            missing: missing.join(", "),
        })
    }
}

/// `<vault>/AGENTS.md` when it exists, otherwise the built-in text.
pub fn load_source(vault: &Path) -> Result<Source, AgentsError> {
    let path = vault.join(FILE_NAME);
    let bad = |reason: &str| AgentsError::BadSource {
        path: path.clone(),
        reason: reason.to_string(),
    };
    let meta = match fs_err::metadata(&path) {
        Ok(meta) => meta,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(Source::builtin()),
        Err(e) => return Err(e.into()),
    };
    if !meta.is_file() {
        return Err(bad("is not a file"));
    }
    if meta.len() > MAX_BYTES {
        return Err(bad("is larger than 64 KiB"));
    }
    let text = String::from_utf8(fs_err::read(&path)?).map_err(|_| bad("is not valid UTF-8"))?;
    let text = normalise(&text);
    if text.is_empty() {
        return Err(bad("is empty"));
    }
    if text
        .lines()
        .any(|line| line.starts_with(BEGIN_PREFIX) || line == END_LINE)
    {
        return Err(bad(
            "contains the autogenerated markers, which would break the block in the projects",
        ));
    }
    Ok(Source {
        text,
        origin: Origin::Vault(path),
    })
}

/// `\n` line ends, no byte order mark, no blank lines around the text.
fn normalise(text: &str) -> String {
    text.trim_start_matches('\u{feff}')
        .replace("\r\n", "\n")
        .trim_matches('\n')
        .trim_end()
        .to_string()
}
