use super::AgentsError;
use super::text::{BUILTIN_SKILLS, Origin, Source, load_source};
use crate::testutil::TempTree;

#[test]
fn the_built_in_text_is_the_five_points_with_the_typos_fixed() {
    let text = Source::builtin().text().to_string();

    assert!(text.starts_with("# Coding related\n"));
    for point in ["1. ", "2. ", "3. ", "4. ", "5. "] {
        assert!(
            text.contains(&format!("\n{point}")),
            "missing point {point}"
        );
    }
    assert!(text.contains("very descriptive error messages"));
    assert!(text.contains("They help others understand decisions"));
    assert!(text.contains("unless the user asks for them"));
    for typo in ["desriptive", "the help others", "except asked"] {
        assert!(!text.contains(typo), "typo is back: {typo}");
    }
}

#[test]
fn the_file_tree_point_names_both_skills() {
    let text = Source::builtin().text().to_string();
    let point = text.lines().find(|l| l.starts_with("2. ")).unwrap();

    assert!(point.contains("`coding`"));
    assert!(point.contains("`file-tree-optimization`"));
}

#[test]
fn every_skill_the_built_in_text_names_is_in_the_required_list_and_the_other_way_round() {
    let text = Source::builtin().text().to_string();

    for skill in BUILTIN_SKILLS {
        assert!(
            text.contains(&format!("`{skill}`")),
            "{skill} is required but not named"
        );
    }
    let named: Vec<&str> = text
        .split('`')
        .enumerate()
        .filter(|(i, _)| i % 2 == 1)
        .map(|(_, s)| s)
        .collect();
    assert_eq!(
        named.len(),
        BUILTIN_SKILLS.len(),
        "the text names {named:?}"
    );
}

#[test]
fn the_built_in_text_is_normalised_and_has_no_markers() {
    let source = Source::builtin();

    assert!(!source.text().contains('\r'));
    assert!(!source.text().ends_with('\n'));
    assert!(!source.text().contains("skillmirror:autogenerated"));
    assert_eq!(source.origin(), &Origin::Builtin);
    assert_eq!(source.required_skills(), BUILTIN_SKILLS);
}

#[test]
fn a_vault_without_the_file_gives_the_built_in_text() {
    let vault = TempTree::new();

    assert_eq!(load_source(vault.path()).unwrap(), Source::builtin());
}

#[test]
fn the_vault_file_wins_and_is_normalised() {
    let vault = TempTree::new();
    vault.write("AGENTS.md", "\u{feff}\n\n# Mine\r\n\r\n1. one\r\n\r\n\r\n");

    let source = load_source(vault.path()).unwrap();

    assert_eq!(source.text(), "# Mine\n\n1. one");
    assert_eq!(
        source.origin(),
        &Origin::Vault(vault.path().join("AGENTS.md"))
    );
    assert!(
        source.required_skills().is_empty(),
        "a vault text is not checked"
    );
}

fn bad_reason(vault: &TempTree) -> String {
    match load_source(vault.path()) {
        Err(AgentsError::BadSource { reason, .. }) => reason,
        other => panic!("expected BadSource, got {other:?}"),
    }
}

#[test]
fn an_empty_vault_file_is_an_error_not_the_built_in_text() {
    let vault = TempTree::new();
    vault.write("AGENTS.md", "  \n\n");

    assert_eq!(bad_reason(&vault), "is empty");
}

#[test]
fn a_vault_file_with_the_markers_is_refused() {
    let vault = TempTree::new();
    vault.write(
        "AGENTS.md",
        "text\n<!-- skillmirror:autogenerated end -->\n",
    );

    assert!(bad_reason(&vault).contains("autogenerated markers"));
}

#[test]
fn a_vault_file_that_is_not_utf8_or_not_a_file_or_too_big_is_refused() {
    let vault = TempTree::new();
    std::fs::write(vault.path().join("AGENTS.md"), [0xff, 0xfe, 0x41]).unwrap();
    assert_eq!(bad_reason(&vault), "is not valid UTF-8");

    std::fs::remove_file(vault.path().join("AGENTS.md")).unwrap();
    std::fs::create_dir(vault.path().join("AGENTS.md")).unwrap();
    assert_eq!(bad_reason(&vault), "is not a file");

    std::fs::remove_dir(vault.path().join("AGENTS.md")).unwrap();
    std::fs::write(vault.path().join("AGENTS.md"), "x".repeat(70 * 1024)).unwrap();
    assert_eq!(bad_reason(&vault), "is larger than 64 KiB");
}
