//! The text the projects share: `agents seed`, where the vault keeps it, and the note at the end of the block.
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::indexing_slicing)]
mod common;

use common::{json_of, skillmirror};
use predicates::prelude::PredicateBooleanExt;
use predicates::str::contains;
use skillmirror_testkit::World;

const END: &str = "<!-- skillmirror:autogenerated end -->";

/// The standard world whose vault also has the three skills the built-in text names, all mandatory.
fn world() -> World {
    let world = World::standard();
    world
        .vault_file("doc-start/SKILL.md", "doc-start v1")
        .vault_file("file-tree-optimization/SKILL.md", "ftree v1")
        .vault_config(&["coding", "tmux", "doc-start", "file-tree-optimization"])
        .commit_vault();
    world
}

fn project(world: &World, name: &str) -> std::path::PathBuf {
    world.root().join(name)
}

// ---- seed ---------------------------------------------------------------------------------------------

#[test]
fn seed_writes_the_built_in_text_into_the_vault_folder_and_says_what_comes_next() {
    let world = world();

    skillmirror(&world)
        .args(["agents", "seed"])
        .assert()
        .success()
        .stdout(contains("Wrote the built-in text to"))
        .stdout(contains("project-files/AGENTS.md"))
        .stdout(contains("agents sync"));

    let text = world.read("vault/project-files/AGENTS.md");
    assert!(text.starts_with("# Coding related\n"), "{text}");
    assert!(text.ends_with('\n') && !text.contains("skillmirror:autogenerated"));
}

#[test]
fn after_seeding_the_vault_text_is_the_source_and_every_project_is_still_in_step() {
    let world = world();
    let fresh = project(&world, "fresh");
    skillmirror(&world)
        .arg("init")
        .arg(&fresh)
        .arg("--yes")
        .assert()
        .success();

    skillmirror(&world)
        .args(["agents", "seed"])
        .assert()
        .success();

    // The same words, now read from the vault: the blocks already hold them.
    skillmirror(&world)
        .args(["agents", "status", "--project"])
        .arg(&fresh)
        .assert()
        .success()
        .stdout(contains("project-files/AGENTS.md"))
        .stdout(contains("current"));
}

#[test]
fn seed_never_overwrites_a_text_that_is_there() {
    let world = world();
    world.vault_file("project-files/AGENTS.md", "# My own rules\n");

    skillmirror(&world)
        .args(["agents", "seed"])
        .assert()
        .code(3)
        .stderr(contains("project-files/AGENTS.md already exists"))
        .stderr(contains("agents sync"));

    assert_eq!(
        world.read("vault/project-files/AGENTS.md"),
        "# My own rules\n"
    );
}

#[test]
fn seed_dry_run_names_the_file_and_writes_nothing() {
    let world = world();

    skillmirror(&world)
        .args(["agents", "seed", "--dry-run"])
        .assert()
        .success()
        .stdout(contains("Would write the built-in text to"))
        .stdout(contains("project-files/AGENTS.md"));

    assert!(!world.exists("vault/project-files"));
}

#[test]
fn seed_dry_run_refuses_for_the_same_reason_the_real_run_does() {
    let world = world();
    world.vault_file("project-files/AGENTS.md", "x");

    skillmirror(&world)
        .args(["agents", "seed", "--dry-run"])
        .assert()
        .code(3)
        .stderr(contains("already exists"));
}

#[test]
fn seed_json_is_one_document() {
    let world = world();

    let document = json_of(skillmirror(&world).args(["agents", "seed", "--json"]));

    assert_eq!(document["command"], "agents seed");
    assert_eq!(document["dry_run"], false);
    assert!(
        document["path"]
            .as_str()
            .unwrap()
            .ends_with("project-files/AGENTS.md")
    );
    assert!(world.exists("vault/project-files/AGENTS.md"));
}

// ---- where the vault keeps the text ------------------------------------------------------------------

#[test]
fn an_agents_file_at_the_vault_root_is_the_vaults_own_and_is_not_the_text() {
    let world = world();
    world.vault_file("AGENTS.md", "# How to work on the vault itself\n");

    skillmirror(&world)
        .args(["agents", "status"])
        .assert()
        .stdout(contains("the built-in text"))
        .stdout(contains("How to work on the vault").not());
}

#[test]
fn the_folder_of_the_text_is_no_skill_and_no_group() {
    let world = world();
    skillmirror(&world)
        .args(["agents", "seed"])
        .assert()
        .success();

    let listed = json_of(skillmirror(&world).args(["skills", "--json"])).to_string();

    assert!(!listed.contains("project-files"), "{listed}");
}

// ---- the note at the end of the block -----------------------------------------------------------------

#[test]
fn a_new_file_ends_its_block_with_the_note_about_what_may_be_changed() {
    let world = world();
    let fresh = project(&world, "fresh");

    skillmirror(&world)
        .arg("init")
        .arg(&fresh)
        .arg("--yes")
        .assert()
        .success();

    let text = std::fs::read_to_string(fresh.join("AGENTS.md")).unwrap();
    let before_end = text.strip_suffix(&format!("{END}\n")).unwrap();
    assert!(
        before_end.ends_with("please change only what comes below it.*\n"),
        "{text}"
    );
    assert!(before_end.contains("\n---\n\n*Managed by skillmirror."));
}

#[test]
fn the_note_stays_when_the_vault_text_changes_and_what_is_below_it_is_left_alone() {
    let world = world();
    world.vault_file("project-files/AGENTS.md", "# Rules\n\n1. old\n");
    world.commit_vault();
    let one = project(&world, "one");
    skillmirror(&world)
        .args(["agents", "add", "--yes", "--project"])
        .arg(&one)
        .assert()
        .success();
    let mut mine = std::fs::read_to_string(one.join("AGENTS.md")).unwrap();
    mine.push_str("\n## This project\n\nOnly runs on Linux.\n");
    std::fs::write(one.join("AGENTS.md"), &mine).unwrap();

    world.vault_file("project-files/AGENTS.md", "# Rules\n\n1. new\n");
    skillmirror(&world)
        .args(["agents", "sync", "--yes", "--project"])
        .arg(&one)
        .assert()
        .success();

    let now = std::fs::read_to_string(one.join("AGENTS.md")).unwrap();
    assert!(now.contains("1. new") && !now.contains("1. old"), "{now}");
    assert!(now.contains("*Managed by skillmirror."), "{now}");
    assert!(
        now.ends_with("\n## This project\n\nOnly runs on Linux.\n"),
        "{now}"
    );
}

// ---- the line `status` adds ----------------------------------------------------------------------------

/// A world with a project whose block was written from "old", then a vault text that says "new".
fn world_behind(edit_block_by_hand: bool) -> World {
    let world = world();
    world.vault_file("project-files/AGENTS.md", "# Rules\n\n1. old\n");
    world.commit_vault();
    let one = project(&world, "one");
    skillmirror(&world)
        .args(["agents", "add", "--yes", "--project"])
        .arg(&one)
        .assert()
        .success();
    if edit_block_by_hand {
        let text = std::fs::read_to_string(one.join("AGENTS.md")).unwrap();
        std::fs::write(one.join("AGENTS.md"), text.replace("1. old", "1. mine")).unwrap();
    }
    world.vault_file("project-files/AGENTS.md", "# Rules\n\n1. new\n");
    world
}

#[test]
fn status_says_how_many_blocks_are_behind_the_text_and_what_to_run() {
    let world = world_behind(false);

    skillmirror(&world)
        .arg("status")
        .assert()
        .stdout(contains("AGENTS.md blocks: 1 out of date."))
        .stdout(contains("agents sync"));
}

#[test]
fn status_names_a_hand_edited_block_separately() {
    let world = world_behind(true);

    skillmirror(&world)
        .arg("status")
        .assert()
        .stdout(contains("AGENTS.md blocks: 1 edited by hand."));
}

#[test]
fn status_stays_quiet_about_blocks_that_are_current_or_missing() {
    let world = world();

    skillmirror(&world)
        .arg("status")
        .assert()
        .stdout(contains("AGENTS.md").not());
}

#[test]
fn status_json_is_not_changed_by_the_hint() {
    let world = world_behind(false);

    let document = json_of(skillmirror(&world).args(["status", "--json"]));

    assert!(document.get("projects").is_some() && document.get("summary").is_some());
    assert!(!document.to_string().contains("AGENTS"), "{document}");
}

#[test]
fn status_warns_when_the_text_cannot_be_used_and_still_reports_the_skills() {
    let world = world();
    world.vault_file("project-files/AGENTS.md", "   \n");

    skillmirror(&world)
        .arg("status")
        .assert()
        .stderr(contains("AGENTS.md:"))
        .stderr(contains("is empty"))
        .stderr(contains("doctor"));
}
