//! `agents add` and `agents sync`: writing the block, and what survives.
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::indexing_slicing)]
mod common;

use common::skillmirror;
use predicates::str::contains;
use skillmirror_testkit::World;

const BEGIN: &str = "<!-- skillmirror:autogenerated begin checksum=";
const END: &str = "<!-- skillmirror:autogenerated end -->";

/// The standard world with its own text in the vault, so no skills are required.
fn world_with_text(text: &str) -> World {
    let world = World::standard();
    world.vault_file("AGENTS.md", text).commit_vault();
    world
}

/// The standard world whose vault also has the three skills the built-in text names, all mandatory.
fn world() -> World {
    let world = World::standard();
    world
        .vault_file("doc-start/SKILL.md", "doc-start v1")
        .vault_file("file-tree-optimization/SKILL.md", "ftree v1")
        .vault_config(&["coding", "tmux", "doc-start", "file-tree-optimization"])
        .commit_vault();
    world
}

fn project(world: &World, name: &str) -> std::path::PathBuf {
    world.root().join(name)
}

fn agents_file(world: &World, name: &str) -> String {
    std::fs::read_to_string(project(world, name).join("AGENTS.md")).unwrap()
}

// ---- add ----------------------------------------------------------------------------------------------

#[test]
fn add_makes_the_file_and_never_touches_one_that_is_already_current() {
    let world = world_with_text("# Rules\n");
    let one = project(&world, "one");

    skillmirror(&world)
        .args(["agents", "add", "--yes", "--project"])
        .arg(&one)
        .assert()
        .success()
        .stdout(contains("created"));
    let first = agents_file(&world, "one");

    skillmirror(&world)
        .args(["agents", "add", "--yes", "--project"])
        .arg(&one)
        .assert()
        .success()
        .stdout(contains("0 to change, 1 unchanged"));
    assert_eq!(agents_file(&world, "one"), first);
}

#[test]
fn add_puts_the_block_in_front_of_a_file_without_one_and_keeps_every_other_byte() {
    let world = world_with_text("# Rules\n");
    let mine = "# One\n\nmy notes\n\twith a tab\n";
    std::fs::write(project(&world, "one").join("AGENTS.md"), mine).unwrap();

    skillmirror(&world)
        .args(["agents", "add", "--yes", "--project"])
        .arg(project(&world, "one"))
        .assert()
        .success()
        .stdout(contains("inserted"));

    let text = agents_file(&world, "one");
    assert!(text.starts_with(BEGIN));
    assert!(text.ends_with(&format!("{END}\n\n{mine}")), "{text}");
}

#[test]
fn add_with_the_built_in_text_needs_the_three_skills_in_the_project() {
    let world = world();
    let one = project(&world, "one");

    skillmirror(&world)
        .args(["agents", "add", "--yes", "--project"])
        .arg(&one)
        .assert()
        .code(3)
        .stderr(contains("doc-start, file-tree-optimization"));
    assert!(!one.join("AGENTS.md").exists());

    skillmirror(&world)
        .args([
            "add",
            "doc-start",
            "file-tree-optimization",
            "--yes",
            "--project",
        ])
        .arg(&one)
        .assert()
        .success();
    skillmirror(&world)
        .args(["agents", "add", "--yes", "--project"])
        .arg(&one)
        .assert()
        .success();
    assert!(agents_file(&world, "one").contains("# Coding related"));
}

#[test]
fn add_refuses_to_write_without_a_terminal_or_yes_and_json_cannot_ask() {
    let world = world_with_text("# Rules\n");
    let one = project(&world, "one");

    skillmirror(&world)
        .args(["agents", "add", "--project"])
        .arg(&one)
        .assert()
        .code(2)
        .stderr(contains("refusing to write without confirmation"));
    skillmirror(&world)
        .args(["agents", "add", "--json", "--project"])
        .arg(&one)
        .assert()
        .code(2)
        .stderr(contains("--json cannot ask for confirmation"));
    assert!(!one.join("AGENTS.md").exists());
}

// ---- sync ---------------------------------------------------------------------------------------------

fn written_world() -> World {
    let world = world_with_text("# Rules\n\n1. old\n");
    for name in ["one", "two"] {
        skillmirror(&world)
            .args(["agents", "add", "--yes", "--project"])
            .arg(project(&world, name))
            .assert()
            .success();
    }
    world
}

#[test]
fn sync_rewrites_only_the_block_everywhere_and_the_rest_of_each_file_stays() {
    let world = written_world();
    let one = project(&world, "one").join("AGENTS.md");
    std::fs::write(
        &one,
        format!("{}\n## Mine\nkeep\n", agents_file(&world, "one")),
    )
    .unwrap();
    world.vault_file("AGENTS.md", "# Rules\n\n1. new\n");

    skillmirror(&world)
        .args(["agents", "sync", "--yes"])
        .assert()
        .success()
        .stdout(contains("2 changed"))
        .stdout(contains("Backup: run"));

    let text = agents_file(&world, "one");
    assert!(text.contains("1. new") && !text.contains("1. old"));
    assert!(text.ends_with("\n## Mine\nkeep\n"), "{text}");
    skillmirror(&world)
        .args(["agents", "status"])
        .assert()
        .stdout(contains("2 current"));
}

#[test]
fn sync_dry_run_shows_the_diff_and_writes_nothing() {
    let world = written_world();
    world.vault_file("AGENTS.md", "# Rules\n\n1. new\n");
    let before = agents_file(&world, "one");

    skillmirror(&world)
        .args(["agents", "sync", "--dry-run", "--diff"])
        .assert()
        .success()
        .stdout(contains("-1. old"))
        .stdout(contains("+1. new"))
        .stdout(contains("2 to change"));

    assert_eq!(agents_file(&world, "one"), before);
}

#[test]
fn sync_stops_for_a_block_edited_by_hand_and_force_replaces_it_and_undo_brings_it_back() {
    let world = written_world();
    let edited = agents_file(&world, "one").replace("1. old", "1. old and mine");
    std::fs::write(project(&world, "one").join("AGENTS.md"), &edited).unwrap();
    world.vault_file("AGENTS.md", "# Rules\n\n1. new\n");

    skillmirror(&world)
        .args(["agents", "sync", "--yes"])
        .assert()
        .code(4)
        .stdout(contains("edited by hand"))
        .stdout(contains("--force"));
    assert_eq!(
        agents_file(&world, "one"),
        edited,
        "the hand edit survives a plain sync"
    );
    assert!(
        agents_file(&world, "two").contains("1. new"),
        "the other project is still updated"
    );

    skillmirror(&world)
        .args(["agents", "sync", "--force", "--yes", "--project"])
        .arg(project(&world, "one"))
        .assert()
        .success();
    assert!(agents_file(&world, "one").contains("1. new"));

    skillmirror(&world)
        .args(["undo", "--yes"])
        .assert()
        .success()
        .stdout(contains("1 item restored"));
    assert_eq!(
        agents_file(&world, "one"),
        edited,
        "undo brings the hand edit back"
    );
}

#[test]
fn history_names_the_run_agents() {
    let world = written_world();

    skillmirror(&world)
        .arg("history")
        .assert()
        .success()
        .stdout(contains("agents"));
}

#[test]
fn a_link_in_place_of_the_file_is_never_written_through() {
    let world = world_with_text("# Rules\n");
    let one = project(&world, "one");
    std::fs::write(world.path().join("elsewhere.md"), "not ours").unwrap();
    std::os::unix::fs::symlink(world.path().join("elsewhere.md"), one.join("AGENTS.md")).unwrap();

    skillmirror(&world)
        .args(["agents", "add", "--yes", "--project"])
        .arg(&one)
        .assert()
        .code(4)
        .stdout(contains("is a link"));

    assert_eq!(
        std::fs::read_to_string(world.path().join("elsewhere.md")).unwrap(),
        "not ours"
    );
}
