//! `init` with an AGENTS.md, and `agents status`, `agents sync` and `agents add`.
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::indexing_slicing)]
mod common;

use common::{json_of, skillmirror};
use predicates::str::contains;
use skillmirror_testkit::World;

const BEGIN: &str = "<!-- skillmirror:autogenerated begin checksum=";
const END: &str = "<!-- skillmirror:autogenerated end -->";

/// The standard world whose vault also has the three skills the built-in text names, all mandatory.
fn world() -> World {
    let world = World::standard();
    world
        .vault_file("doc-start/SKILL.md", "doc-start v1")
        .vault_file("file-tree-optimization/SKILL.md", "ftree v1")
        .vault_config(&["coding", "tmux", "doc-start", "file-tree-optimization"])
        .commit_vault();
    world
}

/// The standard world with its own text in the vault, so no skills are required.
fn world_with_text(text: &str) -> World {
    let world = World::standard();
    world
        .vault_file("project-files/AGENTS.md", text)
        .commit_vault();
    world
}

fn project(world: &World, name: &str) -> std::path::PathBuf {
    world.root().join(name)
}

// ---- init ---------------------------------------------------------------------------------------------

#[test]
fn init_writes_the_file_with_the_block_next_to_the_mandatory_skills() {
    let world = world();
    let fresh = project(&world, "fresh");

    skillmirror(&world)
        .arg("init")
        .arg(&fresh)
        .arg("--yes")
        .assert()
        .success()
        .stdout(contains("AGENTS.md"))
        .stdout(contains("created (from the built-in text)"))
        .stdout(contains("Backup: run"));

    let text = std::fs::read_to_string(fresh.join("AGENTS.md")).unwrap();
    assert!(text.starts_with(BEGIN), "{text}");
    assert!(text.contains("# Coding related"));
    assert!(text.trim_end().ends_with(END));
    for skill in ["coding", "doc-start", "file-tree-optimization", "tmux"] {
        assert!(fresh.join(".agents/skills").join(skill).is_dir(), "{skill}");
    }
}

#[test]
fn init_dry_run_lists_the_file_and_writes_nothing() {
    let world = world();
    let fresh = project(&world, "fresh");

    skillmirror(&world)
        .arg("init")
        .arg(&fresh)
        .arg("--dry-run")
        .assert()
        .success()
        .stdout(contains("AGENTS.md"))
        .stdout(contains("create (from the built-in text)"));

    assert!(!fresh.exists());
}

#[test]
fn init_json_has_an_agents_row_unless_the_file_is_switched_off() {
    let world = world();
    let fresh = project(&world, "fresh");

    let with = json_of(
        skillmirror(&world)
            .arg("init")
            .arg(&fresh)
            .args(["--dry-run", "--json"]),
    );
    let without = json_of(skillmirror(&world).arg("init").arg(&fresh).args([
        "--dry-run",
        "--json",
        "--no-agents-md",
    ]));

    assert_eq!(with["agents"]["action"], "create");
    assert_eq!(with["agents"]["state"], "missing");
    assert!(without.get("agents").is_none(), "{without}");
}

#[test]
fn init_no_agents_md_makes_no_file() {
    let world = world();
    let fresh = project(&world, "fresh");

    skillmirror(&world)
        .arg("init")
        .arg(&fresh)
        .args(["--yes", "--no-agents-md"])
        .assert()
        .success();

    assert!(!fresh.join("AGENTS.md").exists());
    assert!(fresh.join(".agents/skills/coding").is_dir());
}

#[test]
fn init_stops_before_making_anything_when_the_text_names_skills_the_project_would_lack() {
    let world = World::standard();
    let fresh = project(&world, "fresh");

    skillmirror(&world)
        .arg("init")
        .arg(&fresh)
        .arg("--yes")
        .assert()
        .code(3)
        .stderr(contains("doc-start, file-tree-optimization"))
        .stderr(contains("mandatory add doc-start file-tree-optimization"))
        .stderr(contains("--no-agents-md"));

    assert!(!fresh.exists(), "nothing was made");
}

#[test]
fn init_uses_the_vault_text_and_does_not_check_skills_for_it() {
    let world = world_with_text("# Mine\n\n1. my rule\n");
    let fresh = project(&world, "fresh");

    skillmirror(&world)
        .arg("init")
        .arg(&fresh)
        .arg("--yes")
        .assert()
        .success()
        .stdout(contains("created (from "))
        .stdout(contains("vault/project-files/AGENTS.md)"));

    let text = std::fs::read_to_string(fresh.join("AGENTS.md")).unwrap();
    assert!(text.contains("# Mine\n\n1. my rule\n"), "{text}");
    assert!(!text.contains("Coding related"));
}

#[test]
fn init_with_a_vault_text_that_cannot_be_used_is_a_hard_error_not_the_built_in_text() {
    let world = world_with_text("   \n");
    let fresh = project(&world, "fresh");

    skillmirror(&world)
        .arg("init")
        .arg(&fresh)
        .arg("--yes")
        .assert()
        .code(3)
        .stderr(contains("is empty"))
        .stderr(contains("--no-agents-md").not());

    assert!(!fresh.exists());
}

use predicates::prelude::PredicateBooleanExt;

// ---- status -------------------------------------------------------------------------------------------

#[test]
fn status_says_what_each_project_has_and_exits_1_while_something_is_not_current() {
    let world = world_with_text("# Rules\n\n1. a\n");
    skillmirror(&world)
        .args(["agents", "add", "--yes", "--project"])
        .arg(project(&world, "one"))
        .assert()
        .success();
    std::fs::write(project(&world, "two").join("AGENTS.md"), "all mine\n").unwrap();

    skillmirror(&world)
        .args(["agents", "status"])
        .assert()
        .code(1)
        .stdout(contains("text: "))
        .stdout(contains("two").and(contains("no block")))
        .stdout(contains("three").and(contains("missing")))
        .stdout(contains(
            "1 current, 1 without AGENTS.md, 1 without a block in 3 projects",
        ));
}

#[test]
fn status_is_clean_when_every_project_has_the_current_block() {
    let world = world_with_text("# Rules\n");
    for name in ["one", "two", "three"] {
        skillmirror(&world)
            .args(["agents", "add", "--yes", "--project"])
            .arg(project(&world, name))
            .assert()
            .success();
    }

    skillmirror(&world)
        .args(["agents", "status"])
        .assert()
        .success()
        .stdout(contains("3 current in 3 projects"));
}

#[test]
fn status_json_gives_states_and_counts() {
    let world = world_with_text("# Rules\n");
    skillmirror(&world)
        .args(["agents", "add", "--yes", "--project"])
        .arg(project(&world, "one"))
        .assert()
        .success();

    let doc = json_of(skillmirror(&world).args(["agents", "status", "--json"]));

    assert_eq!(doc["summary"]["projects"], 3);
    assert_eq!(doc["summary"]["current"], 1);
    assert_eq!(doc["summary"]["missing"], 2);
    let states: Vec<&str> = doc["projects"]
        .as_array()
        .unwrap()
        .iter()
        .map(|p| p["state"].as_str().unwrap())
        .collect();
    assert_eq!(states.iter().filter(|s| **s == "current").count(), 1);
    assert!(doc["source"].as_str().unwrap().ends_with("AGENTS.md"));
}

#[test]
fn status_exits_4_for_a_file_it_cannot_use() {
    let world = world_with_text("# Rules\n");
    std::fs::write(project(&world, "one").join("AGENTS.md"), format!("{END}\n")).unwrap();

    skillmirror(&world)
        .args(["agents", "status", "--project"])
        .arg(project(&world, "one"))
        .assert()
        .code(4)
        .stdout(contains("broken: an end marker at line 1"));
}
