//! The Agents page: the AGENTS.md of every project, and writing the autogenerated block into some.

use skillmirror_core::agents::{Intent, apply_agents, load_source, plan_agents};
use skillmirror_core::events::ignore_events;
use skillmirror_testkit::World;

use super::{Harness, phase_name};
use crate::app::Screen;
use crate::input::Code;

const ONE: &str = "projects/one/AGENTS.md";
const TWO: &str = "projects/two/AGENTS.md";
const THREE: &str = "projects/three/AGENTS.md";

/// Writes the block into a project with the text the vault has now.
fn write_block(world: &World, project: &str) {
    let source = load_source(&world.vault()).unwrap();
    let plan = plan_agents(&[world.root().join(project)], &source, Intent::ADD);
    assert_eq!(apply_agents(&plan, None, 0, &ignore_events).wrote(), 1);
}

/// `one` is current, `two` has a block from an older text, `three` has no file.
fn world() -> World {
    let world = World::standard();
    world.vault_file("project-files/AGENTS.md", "# Rules\n\n1. old\n");
    write_block(&world, "two");
    world.vault_file("project-files/AGENTS.md", "# Rules\n\n1. new\n");
    write_block(&world, "one");
    world
}

fn work_of(ui: &Harness) -> &crate::screens::Work {
    let Screen::Work(work) = &ui.app.screen else {
        panic!("a work page, not {}", phase_name(&ui.app))
    };
    work
}

#[test]
fn the_page_lists_every_project_with_its_state_and_ticks_only_the_outdated_ones() {
    let mut ui = Harness::new(world());
    ui.open("Agents").wait_select();

    let screen = ui.screen();

    for expected in [
        "Select projects to write the AGENTS.md block into",
        "1 / 3 selected",
        "project",
        "state",
        "up to date",
        "the vault text changed",
        "no AGENTS.md yet",
    ] {
        assert!(screen.contains(expected), "{expected}:\n{screen}");
    }
    let work = work_of(&ui);
    let ticked: Vec<&str> = work
        .selected
        .iter()
        .map(|i| work.items[*i].detail.as_str())
        .collect();
    assert_eq!(ticked, ["outdated"]);
}

#[test]
fn the_page_as_snapshot() {
    let mut ui = Harness::sized(world(), 100, 20);
    ui.open("Agents").wait_select();

    insta::assert_snapshot!(ui.screen());
}

#[test]
fn enter_plans_then_asks_and_shows_the_changes_before_anything_is_written() {
    let world = world();
    let before = world.read(TWO);
    let mut ui = Harness::new(world);
    ui.open("Agents").wait_select();

    ui.code(Code::Enter).wait_confirm();
    let question = ui.screen();
    assert!(
        question.contains("Write AGENTS.md in 1 project?"),
        "{question}"
    );
    assert!(
        question.contains("Rewrites the block in 1 AGENTS.md file."),
        "{question}"
    );
    assert!(question.contains("rest stays"), "{question}");
    assert!(
        question.contains("v "),
        "the footer offers the changes, as it does for a sync:\n{question}"
    );
    assert_eq!(ui.world.read(TWO), before, "asking writes nothing");

    ui.press('v');
    ui.wait_for("the changes page", |app| phase_name(app) == "diff");
    let diff = ui.screen();
    assert!(diff.contains("AGENTS.md in projects/two"), "{diff}");
    assert!(
        diff.contains("-1. old") && diff.contains("+1. new"),
        "{diff}"
    );
    assert_eq!(
        ui.world.read(TWO),
        before,
        "reading the changes writes nothing"
    );

    ui.press('v');
    assert_eq!(phase_name(&ui.app), "confirm", "back to the same question");
}

#[test]
fn the_question_as_snapshot() {
    let mut ui = Harness::sized(world(), 100, 20);
    ui.open("Agents").wait_select();
    ui.code(Code::Enter).wait_confirm();

    insta::assert_snapshot!(ui.screen());
}

#[test]
fn yes_writes_only_the_block_and_the_results_say_so() {
    let world = world();
    let mine = format!("{}\n## Mine\nkeep this\n", world.read(TWO));
    std::fs::write(world.root().join("two/AGENTS.md"), &mine).unwrap();
    let mut ui = Harness::new(world);
    ui.open("Agents").wait_select();

    ui.run_confirmed();
    let results = ui.screen();

    assert!(results.contains("Agents file results"), "{results}");
    assert!(results.contains("AGENTS.md"), "{results}");
    assert!(results.contains("written to 1 project"), "{results}");
    let two = ui.world.read(TWO);
    assert!(two.contains("1. new") && !two.contains("1. old"), "{two}");
    assert!(two.ends_with("\n## Mine\nkeep this\n"), "{two}");
    assert!(
        !ui.world.exists(THREE),
        "the project that was not ticked is untouched"
    );
    assert!(
        results.contains("Backup") || results.contains("undo"),
        "{results}"
    );
}

#[test]
fn history_lists_the_run_and_undoing_it_brings_the_old_text_back() {
    let world = world();
    let old = world.read(TWO);
    let mut ui = Harness::new(world);
    ui.open("Agents").wait_select();
    ui.run_confirmed();
    assert_ne!(ui.world.read(TWO), old);
    ui.press('q');

    ui.open("History");
    ui.wait_for("the list of runs", |app| phase_name(app) == "history");
    ui.wait_for("a run in the list", |app| {
        matches!(&app.screen, Screen::History(h) if matches!(h.phase, crate::screens::HistoryPhase::List))
    });
    assert!(ui.screen().contains("agents"), "{}", ui.screen());
    ui.code(Code::Enter);
    ui.wait_for("the question", |app| {
        matches!(&app.screen, Screen::History(h) if matches!(h.phase, crate::screens::HistoryPhase::Confirm(_)))
    });
    assert!(ui.screen().contains("AGENTS.md"), "{}", ui.screen());
    ui.press('y');
    ui.wait_for("the results", |app| {
        matches!(&app.screen, Screen::History(h) if matches!(h.phase, crate::screens::HistoryPhase::Done(_)))
    });

    assert_eq!(ui.world.read(TWO), old);
}

#[test]
fn a_missing_file_can_be_ticked_and_is_made() {
    let world = World::standard();
    world.vault_file("project-files/AGENTS.md", "# Rules\n");
    let mut ui = Harness::new(world);
    ui.open("Agents").wait_select();
    assert_eq!(
        work_of(&ui).selected.len(),
        0,
        "making files is the user's choice"
    );

    ui.press(' ').code(Code::Enter).wait_confirm();
    let question = ui.screen();
    assert!(
        question.contains("Makes or starts 1 AGENTS.md file."),
        "{question}"
    );
    ui.press('y').wait_done();

    let made = ui.world.read(ONE);
    assert!(made.contains("# Rules"), "{made}");
}

#[test]
fn the_built_in_text_is_not_written_into_a_project_without_the_skills_it_names() {
    let mut ui = Harness::new(World::standard());
    ui.open("Agents").wait_select();

    // Nothing could be written, so there is nothing to ask: the page goes on and says why.
    ui.press(' ').code(Code::Enter).wait_done();
    let results = ui.screen();

    assert!(
        results.contains("doc-start, file-tree-optimization"),
        "{results}"
    );
    assert!(results.contains("failed"), "{results}");
    assert!(!ui.world.exists(ONE));
}

#[test]
fn a_block_edited_by_hand_is_listed_as_such_and_is_not_overwritten() {
    let world = world();
    let edited = world.read(TWO).replace("1. old", "1. old and mine");
    std::fs::write(world.root().join("two/AGENTS.md"), &edited).unwrap();
    let mut ui = Harness::new(world);
    ui.open("Agents").wait_select();
    let screen = ui.screen();
    assert!(screen.contains("edited by hand"), "{screen}");
    assert_eq!(
        work_of(&ui).selected.len(),
        0,
        "an edited block is not ticked"
    );

    ui.press('j').press('j').press(' ');
    ui.code(Code::Enter).wait_done();
    let results = ui.screen();

    assert!(results.contains("--force"), "{results}");
    assert_eq!(ui.world.read(TWO), edited);
}

#[test]
fn a_text_that_cannot_be_used_is_the_whole_page() {
    let world = World::standard();
    world.vault_file("project-files/AGENTS.md", "   \n");
    let mut ui = Harness::new(world);
    ui.open("Agents");
    ui.wait_for("the failure", |app| phase_name(app) == "failed");

    let screen = ui.screen();

    assert!(screen.contains("is empty"), "{screen}");
    ui.code(Code::Esc);
    assert_eq!(phase_name(&ui.app), "menu");
}

#[test]
fn leaving_the_page_puts_the_cursor_on_its_menu_entry() {
    let mut ui = Harness::new(world());
    ui.open("Agents").wait_select();

    ui.press('q');

    let Screen::Menu(menu) = &ui.app.screen else {
        panic!("the menu")
    };
    assert_eq!(crate::screens::ENTRIES[menu.cursor].label, "Agents");
}
