//! Init through the interface with its AGENTS.md: made in the same confirmed run as the skills, in the
//! same backup run, and only when the text can be used and its skills are among the ones ticked.

use skillmirror_core::backup::{Backups, Subject};
use skillmirror_core::config::Dirs;
use skillmirror_testkit::World;

use super::{Harness, phase_name, world};
use crate::input::Code;

const FILE: &str = "projects/fresh/AGENTS.md";

/// The standard vault plus the two skills the built-in text names, all four mandatory.
fn world_with_the_named_skills() -> World {
    let world = world();
    world
        .vault_file("doc-start/SKILL.md", "doc-start v1")
        .vault_file("file-tree-optimization/SKILL.md", "ftree v1")
        .vault_config(&["coding", "tmux", "doc-start", "file-tree-optimization"])
        .commit_vault();
    world
}

fn to_the_skills_page(ui: &mut Harness) {
    ui.open("Init");
    ui.code(Code::Enter)
        .type_text("fresh")
        .code(Code::Enter)
        .wait_select();
}

fn failure(ui: &mut Harness) -> String {
    ui.wait_for("the failure", |app| phase_name(app) == "failed");
    ui.screen()
}

#[test]
fn the_file_is_written_with_the_skills_and_both_are_in_one_backup_run() {
    let mut ui = Harness::sized(world_with_the_named_skills(), 100, 30);
    to_the_skills_page(&mut ui);
    assert!(ui.screen().contains("4 / 5 selected"), "{}", ui.screen());

    ui.code(Code::Enter).wait_confirm();
    let question = ui.screen();
    assert!(
        question.contains("Also writes AGENTS.md, from the built-in text."),
        "{question}"
    );
    assert!(!ui.world.exists(FILE), "nothing is written before yes");

    ui.press('v');
    ui.wait_for("the changes page", |app| phase_name(app) == "diff");
    let changes = ui.screen();
    assert!(changes.contains("AGENTS.md in projects/fresh"), "{changes}");
    ui.press('v');

    ui.press('y').wait_done();
    let results = ui.screen();
    assert!(results.contains("Init results"), "{results}");
    assert!(results.contains("AGENTS.md"), "{results}");
    let file = ui.world.read(FILE);
    assert!(
        file.starts_with("<!-- skillmirror:autogenerated begin"),
        "{file}"
    );
    assert!(file.contains("# Coding related"));
    for skill in ["coding", "tmux", "doc-start", "file-tree-optimization"] {
        assert!(
            ui.world
                .exists(&format!("projects/fresh/.agents/skills/{skill}/SKILL.md")),
            "{skill}"
        );
    }

    // One run holds the skills and the file, in separate slots.
    let dirs = Dirs::under(&ui.world.path().join("home"));
    let run = Backups::in_dirs(&dirs).latest().unwrap();
    let indexes: Vec<usize> = run.entries.iter().map(|e| e.index).collect();
    let mut unique = indexes.clone();
    unique.sort_unstable();
    unique.dedup();
    assert_eq!(
        indexes.len(),
        unique.len(),
        "slots are not shared: {indexes:?}"
    );
    assert_eq!(
        run.entries
            .iter()
            .filter(|e| e.entry.subject == Subject::Agents)
            .count(),
        1
    );
    assert_eq!(run.entries.len(), 5, "four skills and the file");
}

#[test]
fn the_vault_text_is_used_and_its_skills_are_not_checked() {
    let world = world();
    world.vault_file("AGENTS.md", "# Mine\n\n1. a rule\n");
    let mut ui = Harness::new(world);
    to_the_skills_page(&mut ui);

    ui.code(Code::Enter).wait_confirm();
    let question = ui.screen();
    assert!(
        question.contains("Also writes AGENTS.md, from"),
        "{question}"
    );
    assert!(
        question.contains("vault/AGENTS.md."),
        "the path of the text is named:\n{question}"
    );
    ui.press('y').wait_done();

    let file = ui.world.read(FILE);
    assert!(file.contains("# Mine\n\n1. a rule\n"), "{file}");
}

#[test]
fn m_leaves_the_file_out_and_the_page_says_so() {
    let mut ui = Harness::new(world_with_the_named_skills());
    to_the_skills_page(&mut ui);

    ui.press('m');
    assert!(ui.screen().contains("no AGENTS.md"), "{}", ui.screen());
    ui.code(Code::Enter).wait_confirm();
    assert!(
        !ui.screen().contains("Also writes AGENTS.md"),
        "{}",
        ui.screen()
    );
    ui.press('y').wait_done();

    assert!(!ui.world.exists(FILE));
    assert!(
        ui.world
            .exists("projects/fresh/.agents/skills/coding/SKILL.md")
    );
}

#[test]
fn m_again_puts_it_back() {
    let mut ui = Harness::new(world_with_the_named_skills());
    to_the_skills_page(&mut ui);

    ui.press('m').press('m');

    assert!(!ui.screen().contains("no AGENTS.md"), "{}", ui.screen());
}

#[test]
fn skills_the_text_names_that_are_not_ticked_stop_the_page_before_anything_is_made() {
    let mut ui = Harness::new(world());
    to_the_skills_page(&mut ui);

    ui.code(Code::Enter);
    let page = failure(&mut ui);

    assert!(page.contains("doc-start, file-tree-optimization"), "{page}");
    assert!(page.contains("press m"), "{page}");
    assert!(!ui.world.exists("projects/fresh"), "nothing was made");
}

#[test]
fn a_text_that_cannot_be_used_stops_the_page_too() {
    let world = world();
    world.vault_file("AGENTS.md", "  \n");
    let mut ui = Harness::new(world);
    to_the_skills_page(&mut ui);

    ui.code(Code::Enter);
    let page = failure(&mut ui);

    assert!(page.contains("is empty"), "{page}");
    assert!(!ui.world.exists("projects/fresh"));
}

#[test]
fn no_file_is_made_when_no_skill_could_be_installed() {
    let world = world();
    world.vault_file("AGENTS.md", "# Mine\n");
    // In the vault but not in git: the plan for it fails, so nothing can be installed.
    world.vault_file("fresh/SKILL.md", "untracked");
    let mut ui = Harness::new(world);
    to_the_skills_page(&mut ui);
    // Untick the mandatory skills, tick the one that cannot be planned.
    ui.press('a').press('a');
    ui.press('j').press('j').press(' ');

    ui.code(Code::Enter).wait_done();

    assert!(ui.screen().contains("failed"), "{}", ui.screen());
    assert!(
        !ui.world.exists("projects/fresh"),
        "the folder was taken back"
    );
    assert!(!ui.world.exists(FILE));
}
