//! The arguments of the `agents` commands: the AGENTS.md of each project.
// Doc comments here become `--help` text, where file names must stay unquoted.
#![allow(clippy::doc_markdown)]

use std::path::PathBuf;

use clap::{Args, Subcommand};

#[derive(Debug, Subcommand)]
pub(crate) enum AgentsCommand {
    /// Show how the AGENTS.md of each project stands against the text; writes nothing, exit 1 when any is not current
    Status(AgentsStatusArgs),
    /// Rewrite the autogenerated block where it is out of date; the rest of each file is never touched
    Sync(AgentsSyncArgs),
    /// Make AGENTS.md in a project that has none, or put the block into one that has no block
    Add(AgentsAddArgs),
}

#[derive(Debug, Args)]
pub(crate) struct AgentsStatusArgs {
    /// Only this project (default: every project under the root)
    #[arg(long, value_name = "DIR")]
    pub(crate) project: Option<PathBuf>,
    /// Also list the projects whose block is current
    #[arg(long)]
    pub(crate) all: bool,
    /// Print one JSON document instead of text
    #[arg(long)]
    pub(crate) json: bool,
}

// Independent command-line switches, not a state machine.
#[allow(clippy::struct_excessive_bools)]
#[derive(Debug, Args)]
pub(crate) struct AgentsSyncArgs {
    /// Only this project (default: every project under the root)
    #[arg(long, value_name = "DIR")]
    pub(crate) project: Option<PathBuf>,
    /// Also replace a block that was edited by hand (the old file is kept for `undo`)
    #[arg(long)]
    pub(crate) force: bool,
    #[command(flatten)]
    pub(crate) flags: AgentsFlags,
}

#[derive(Debug, Args)]
pub(crate) struct AgentsAddArgs {
    /// The project (default: the current directory)
    #[arg(long, value_name = "DIR")]
    pub(crate) project: Option<PathBuf>,
    #[command(flatten)]
    pub(crate) flags: AgentsFlags,
}

/// Flags shared by the two commands that write.
// Independent command-line switches, not a state machine.
#[allow(clippy::struct_excessive_bools)]
#[derive(Debug, Args)]
pub(crate) struct AgentsFlags {
    /// Show what would change and write nothing
    #[arg(long)]
    pub(crate) dry_run: bool,
    /// Write without asking
    #[arg(short = 'y', long)]
    pub(crate) yes: bool,
    /// Show the lines that change in each file
    #[arg(long)]
    pub(crate) diff: bool,
    /// Also list the projects where nothing changes
    #[arg(long)]
    pub(crate) all: bool,
    /// Print one JSON document instead of text
    #[arg(long)]
    pub(crate) json: bool,
}
